### ISSUE TITLE
Playbook does not support running GOCD on :80

### ISSUE THREAD

**Issue by benwaine** [hoborglabs/ansible_gocd_server#1]
When attempting to set `goserver_port` to `80` the following exception is triggered during the restart step (after the new configuration is applied). 

```
java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Net.java:463)
    at sun.nio.ch.Net.bind(Net.java:455)
    at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
    at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
    at org.mortbay.jetty.nio.SelectChannelConnector.open(SelectChannelConnector.java:216)
    at org.mortbay.jetty.nio.SelectChannelConnector.doStart(SelectChannelConnector.java:315)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at org.mortbay.jetty.Server.doStart(Server.java:235)
    at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
    at com.thoughtworks.go.server.JettyServer.start(JettyServer.java:56)
    at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:92)
    at com.thoughtworks.go.server.GoServer.go(GoServer.java:84)
    at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:31)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.simontuffs.onejar.Boot.run(Boot.java:306)
    at com.simontuffs.onejar.Boot.main(Boot.java:159)
log4j:WARN No appenders could be found for logger (com.thoughtworks.go.server.util.H2EventListener).
log4j:WARN Please initialize the log4j system properly.

```

**Comment by woledzki** [comment]
@benwaine gocd is running using no-root account. I will add support for adding `go` user to "sudo users" shortly in https://github.com/ansible-city/gocd_server. 

This repo will be closed/deleted in next few weeks.
